### ISSUE TITLE
还会更新吗？

### ISSUE THREAD

**Issue by wherewhere** [zsakvo/coolapk-chrome-extensions#2]
到现在都还能用，真是太厉害了

**Comment by zsakvo** [comment]
呃……还需要什么吗？
主要是现在感觉酷安没啥好看的，都不用了，所以就没继续更新。。。

**Comment by wherewhere** [comment]
> 呃……还需要什么吗？
> 主要是现在感觉酷安没啥好看的，都不用了，所以就没继续更新。。。

比如打开链接直接看内容啥的，还有就是能不能留一个用app打开😂

**Comment by zsakvo** [comment]
> 比如打开链接直接看内容啥的，还有就是能不能留一个用 app 打开😂

我有空看看吧，但是别抱啥希望。
酷安现在真的没啥意思，没有动力去打开了😂

**Comment by wherewhere** [comment]
> > 比如打开链接直接看内容啥的，还有就是能不能留一个用 app 打开😂
> 
> 我有空看看吧，但是别抱啥希望。
> 酷安现在真的没啥意思，没有动力去打开了😂
> 

好耶！

**Comment by wherewhere** [comment]
诶？你上面UA用的是V10，怎么到下面就成V9了。。。
